version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: dockerfile
    container_name: nextword-api
    ports:
      - "8000:8000"
    # Mount local code to reload on changes (optional, good for dev)
    volumes:
      - ./model:/app/model:ro
    environment:
      TF_CPP_MIN_LOG_LEVEL: "2"

  frontend:
    image: nginx:1.27-alpine
    container_name: nextword-frontend
    depends_on:
      - api
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro

